#!/bin/bash
AWSCRIPKEY='QUtJQVRETFo0VE4yUUhPMzJSSFkK'
AWSCRIPSEC='bitGZnU4TEQ2Yi82U0gxcVhNT09XclNNODNGNDh2QndiUVpvZ01MQgo='

export AWS_ACCESS_KEY_ID=$(echo $AWSCRIPKEY | base64 -d)
echo $AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$(echo $AWSCRIPSEC | base64 -d)
echo $AWS_SECRET_ACCESS_KEY